Version 0.6

diff --git a/lib/svc/method/zfs-auto-snapshot b/lib/svc/method/zfs-auto-snapshot
--- a/lib/svc/method/zfs-auto-snapshot
+++ b/lib/svc/method/zfs-auto-snapshot
@@ -32,9 +32,10 @@
 # all child datasets. More documentation available at
 # http://blogs.sun.com/timf
 #
-# The service will move itself into maintenance if it's unable to take a snapshot,
-# destroy a snapshot as per the snapshot retention policy, or is unable to
-# create or update the cron job.
+# The service will move itself into maintenance if it's unable to take a
+# snapshot, destroy a snapshot as per the snapshot retention policy, unable to
+# zfs send a dataset (if configured) or is unable to create or update the cron
+# job.
 # 
 
 
@@ -61,15 +62,28 @@ result=$SMF_EXIT_OK
 # $1 is assumed to be a valid FMRI
 function schedule_snapshots {
 
-	FMRI=$1
+	typeset FMRI=$1
 	# FIXME need work in here to actually validate the FMRI props
-	FILESYS=$(svcprop -p zfs/fs-name $FMRI)
-	INTERVAL=$(svcprop -p zfs/interval $FMRI)
-	PERIOD=$(svcprop -p zfs/period $FMRI)
-	OFFSET=$(svcprop -p zfs/offset $FMRI)
-	
+	typeset FILESYS=$(svcprop -p zfs/fs-name $FMRI)
+	typeset INTERVAL=$(svcprop -p zfs/interval $FMRI)
+	typeset PERIOD=$(svcprop -p zfs/period $FMRI)
+	typeset OFFSET=$(svcprop -p zfs/offset $FMRI)
+	typeset STATE=0	
+
+	typeset BACKUP=$(svcprop -p zfs/backup $FMRI)
+	typeset BACKUP_SAVE_CMD=$(svcprop -p zfs/backup $FMRI)
+
+	case $BACKUP in
+	'full' | 'incremental' )
+		if [ -z "${BACKUP_SAVE_CMD}" ]
+		then
+		  check_failure 1 "Backup requested, but no backup command specified."
+		fi
+	;;
+	esac
+
 	# for now, we're forcing the offset to be 0 seconds.
-	OFFSET=0
+	typeset OFFSET=0
 
 	# validate the filesystem
 	zfs list $FILESYS 2>&1 1> /dev/null
@@ -105,7 +119,12 @@ function schedule_snapshots {
 # just live with this.
 #
 function add_cron_job { # $INTERVAL $PERIOD $OFFSET $FMRI
-	
+
+	typeset INTERVAL=$1
+	typeset PERIOD=$2
+	typeset OFFSET=$3
+	typeset FMRI=$4
+
 	case $INTERVAL in
 	'minutes')
 		TIMES=$(get_divisor 0 59 $PERIOD)
@@ -145,7 +164,8 @@ function add_cron_job { # $INTERVAL $PERIOD $OFFSET $FMRI
 # $1 is assumed to be a valid FMRI
 function unschedule_snapshots {
 
-	FMRI=$1
+	typeset FMRI=$1
+
 	crontab -l | grep -v "/lib/svc/method/zfs-auto-snapshot $FMRI$" > /tmp/saved-crontab.$$
 	crontab /tmp/saved-crontab.$$
 	check_failure $? "Unable to unschedule snapshots for $FMRI"
@@ -167,29 +187,73 @@ function unschedule_snapshots {
 # $1 is assumed to be a valid FMRI
 function take_snapshot {
 
-	FMRI=$1
+	typeset FMRI=$1
 
-	DATE=$(date +%F-%H:%M:%S)
-	SNAPNAME="zfs-auto-snap-${DATE}"
-	FILESYS=$(svcprop -p zfs/fs-name $FMRI)
-	KEEP=$(svcprop -p zfs/keep $FMRI)
-	SNAP_CHILDREN=$(svcprop -p zfs/snapshot-children $FMRI)
+	typeset DATE=$(date +%F-%H:%M:%S)
+	typeset FILESYS=$(svcprop -p zfs/fs-name $FMRI)
+	typeset KEEP=$(svcprop -p zfs/keep $FMRI)
+	typeset SNAP_CHILDREN=$(svcprop -p zfs/snapshot-children $FMRI)
+
+	typeset BACKUP=$(svcprop -p zfs/backup $FMRI)
+	typeset STATE=0
+
+	# an identifier allows us to setup multiple snapshot schedules
+	# per filesystem - so we append a :<id> token if the user has
+	# requested one, which then gets used in the SNAPNAME.  SMF
+	# returns the value '""' for the empty string to differentiate
+	# between an unset property, and a set-but-empty property.
+	# Shocking, I know.
+	typeset LABEL="$(svcprop -p zfs/label $FMRI)"
+	if [ "$LABEL" != "\"\"" ]
+	then
+		LABEL=":${LABEL}"
+	else
+		LABEL=""
+	fi
+
+	typeset SNAPNAME="zfs-auto-snap${LABEL}-${DATE}"
 	
-	# Ok, now say cheese! It'd be nice if the child snapshotting was
-	# atomic, but we don't yet have that in zfs.
+
+	# Ok, now say cheese! If we're taking recursive snapshots,
+	# walk through the children, destroying old ones if required.
 	if [ "${SNAP_CHILDREN}" == "true" ]
 	then
-	   for child in $(zfs list -r -H -o name -t filesystem $FILESYS)
+
+           OS=$(uname -r)
+	   for child in $(zfs list -r -H -o name -t filesystem,volume $FILESYS)
 	   do
-		destroy_older_snapshots $child $KEEP
-		zfs snapshot $child@$SNAPNAME
-		check_failure $? "Unable to take snapshot $child@$SNAPNAME."
+		destroy_older_snapshots $child $KEEP $LABEL
+		if [ "${OS}" != "5.11" ]
+		then
+		   # Solaris 10 doesn't have recursive snapshots, but we do
+		   # them outside the loop otherwise.
+	     	   zfs snapshot $child@$SNAPNAME
+		   check_failure $? "Unable to take snapshot $child@$SNAPNAME."
+		fi
 	   done
+           # take the recursive snapshots if we're on Solaris Nevada.
+           if [ "${OS}" == "5.11" ]
+	   then
+               zfs snapshot -r $FILESYS@$SNAPNAME
+	       check_failure $? "Unable to take recursive snapshots $FILESYS@$SNAPNAME."
+           fi
+
         else
+
   	   destroy_older_snapshots $FILESYS $KEEP
 	   zfs snapshot $FILESYS@$SNAPNAME
 	   check_failure $? "Unable to take snapshot $FILESYS@$SNAPNAME."
+
 	fi
+
+	# If the user has asked for backups, go ahead and do this.
+	if [ "${BACKUP}" != "none" ]
+	then
+		take_backup $FILESYS $BACKUP "$LABEL" $FMRI
+		check_failure $? "Unable to backup filesystem $FILESYS using \
+				$BACKUP backup strategy."
+	fi
+
 
 	# finally, check our status before we return
 	STATE=$(svcprop -p restarter/state $FMRI)
@@ -202,16 +266,18 @@ function take_snapshot {
 	return $STATE
 }
 
-# Given a filesystem name, and a limit of the number of snapshots we want
+# Given a filesystem name, and a limit of the number of snapshots we want,
+# along with the identifier for this set of snapshots,
 # we destroy all older snapshots of this filesystem whose names begin
-# with the text "zfs-auto-snap". Note that here we destroy one more snapshot
+# with the text "zfs-auto-snap<id>". Note that here we destroy one more snapshot
 # than the "keep" threshold - this is because in the context of calling this
 # function, we're already creating one new auto-snapshot.
 #
 function destroy_older_snapshots {
 
-	FILESYS=$1
-	COUNTER=$2
+	typeset FILESYS=$1
+	typeset COUNTER=$2
+	typeset LABEL=$3
 
 	if [ "${COUNTER}" == "all" ]
 	then
@@ -222,7 +288,7 @@ function destroy_older_snapshots {
 	
 	# walk through the snapshots, newest first, destroying older ones
 	for snapshot in $(zfs list -r -t snapshot -H -o name $FILESYS \
-		 | grep $FILESYS@zfs-auto-snap | sort -r)
+		 | grep "$FILESYS@zfs-auto-snap${LABEL}" | sort -r)
 	do
 		if [ $COUNTER -le 0 ]
 		then
@@ -237,14 +303,15 @@ function destroy_older_snapshots {
 }
 
 # Given the exit status of a command, an integer, 0 if the command completed
-# without errors, if the command exited with errors, then we degrade the
+# without errors. If the command exited with errors, we degrade the
 # state of this service into maintenance mode. We also log an error message
 # as passed into this function.
 #
 function check_failure { # integer exit status, error message to display
   
-   RESULT=$1
-   ERR_MSG=$2
+   typeset RESULT=$1
+   typeset ERR_MSG=$2
+
    if [ $RESULT -ne 0 ]
    then
 	echo "Error: $ERR_MSG"
@@ -261,11 +328,11 @@ function check_failure { # integer exit status, error message to display
 #
 function get_divisor { # start period, end period, width of period
 
-    START=$1
-    END=$2
-    WIDTH=$3
-    RANGE=$START
-    JUMP=$(( $RANGE + $WIDTH ))
+    typeset START=$1
+    typeset END=$2
+    typeset WIDTH=$3
+    typeset RANGE=$START
+    typeset JUMP=$(( $RANGE + $WIDTH ))
 
     while [ $JUMP -lt $END ]
     do
@@ -274,6 +341,114 @@ function get_divisor { # start period, end period, width of period
     done
 	
     echo $RANGE
+}
+
+
+# Given a filesytem name, and a backup type (currently "complete" or
+# "incremental") along with an FMRI, we backup the filesystem - either
+# from the latest snapshot that was taken, or by an incremental backup.
+# Properties in the FMRI tell us what to do with the backup stream
+#
+function take_backup { # filesystem backup-type label fmri
+
+    typeset FILESYS=$1
+    typeset BACKUP=$2
+    typeset LABEL=$3
+    typeset FMRI=$4
+
+
+    # obtain lock from fmri
+    typeset LOCK=$(svcprop -p zfs/backup-lock $FMRI)
+    if [ "$LOCK" != "unlocked" ]
+    then
+	# Unable to perform this backup due to an existing backup being
+	# executed for this dataset. This would result in moving the
+	# service to maintenance mode if we're doing incrementals, but
+	# it's not so serious for full backups.
+        echo "Unable to backup $FILESYS: $LOCK."
+
+	if [ "$BACKUP" == "incremental" ]
+	then
+	     echo "A lock prevented us from performing an incremental backup."
+	     return 1
+	else
+	     echo "Full backup not completed for $FMRI on $(date)."
+	     return 0
+	fi
+    else
+ 	# set our lock. (this isn't atomic, unfortunately :-( )
+        svccfg -s $FMRI setprop zfs/backup-lock = astring: \
+	"\"$BACKUP backup in progress by PID $$\""
+	svcadm refresh $FMRI
+    fi
+
+    typeset BACKUP_SAVE_CMD=$(svcprop -p zfs/backup-save-cmd $FMRI \
+				| sed -e 's/\\//g')
+    typeset SNAP_CHILDREN=$(svcprop -p zfs/snapshot-children $FMRI)
+    typeset BACKUP_DATASETS=""
+
+    # Determine how many datasets we have to backup
+    if [ "$SNAP_CHILDREN" == "true" ]
+    then
+	BACKUP_DATASETS=$(zfs list -r -H -o name -t filesystem,volume $FILESYS)
+    else
+        # only one dataset to worry about here.
+	BACKUP_DATASETS=$FILESYS
+    fi
+
+    # loop through the datasets, backing up each one.
+    for dataset in $BACKUP_DATASETS
+    do
+
+      # An initial check of the input parameters, to see how we should proceed
+      case $BACKUP in
+        "incremental")
+		# get the last two snapshots
+		LAST_SNAP=$(zfs list -H -o name -r -t snapshot $dataset \
+			    | grep "$dataset@zfs-auto-snap${LABEL}" | tail -1)
+
+		PREV_SNAP=$(zfs list -H -o name -r -t snapshot $dataset \
+			    | grep "$dataset@zfs-auto-snap${LABEL}" \
+			    | tail -2 | head -1)
+
+		if [ "$PREV_SNAP" == "$LAST_SNAP" ]
+		then
+		    echo "Previous snap not found of $dataset, taking full backup"
+		    BACKUP="full"
+		fi
+	;;
+        "full")
+ 		LAST_SNAP=$(zfs list -H -o name -r -t snapshot $dataset \
+			    | grep "$dataset@zfs-auto-snap${LABEL}" | tail -1)
+	;;
+        *)
+		check_failure 1 "Unknown backup type $BACKUP"
+		svccfg -s $FMRI setprop zfs/backup-lock = astring: "unlocked"
+		svcadm refresh $FMRI
+		return 1
+	;;
+       esac
+
+ 
+       # Now perform the backup. Note that on errors, we'll immediately mark
+       # the service as being in maintenance mode, however, backups will still 
+       # be attempted for other datasets in our list.
+       case $BACKUP in
+	"incremental")	  
+	    zfs send -i $PREV_SNAP $LAST_SNAP | $BACKUP_SAVE_CMD
+	    check_failure $? "Error performing incremental backup of $dataset."
+	;;
+	"full")
+	    zfs send $LAST_SNAP | $BACKUP_SAVE_CMD
+	    check_failure $? "Error performing full backup of $dataset."
+	;;
+       esac
+   done
+
+   # Now we can release our lock
+   svccfg -s $FMRI setprop zfs/backup-lock = astring: "unlocked"
+   svcadm refresh $FMRI
+
 }
 
 
@@ -313,7 +488,7 @@ case "$1" in
         ;;
 
 # the default case, we actually call from the cron job itself that's
-# executing this script.
+# executing this script, and do the job of taking snapshots.
 *)
 	SMF_FMRI=$1
 	# are we being called with the correct argument (an FMRI) ?
